import Breadcrumb from '@/Components/Breadcrumb';
import Pagination from '@/Components/Pagination';
import AdminLayout from '@/Layouts/AdminLayout';
import { Head, router } from '@inertiajs/react';
import { useState } from 'react';

const date = (value) => value ? new Date(value).toLocaleString('id-ID', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const labels = { pending_parent_approval: 'Menunggu pusat', pending_admin_approval: 'Perlu keputusan', approved_pending_billing: 'Menunggu billing', active: 'Aktif', exit_requested: 'Minta keluar', detached_pending: 'Akan dilepas', detached: 'Dilepas', rejected: 'Ditolak' };

export default function Index({ relationships, filters, centrals, auditLogs }) {
    const [search, setSearch] = useState(filters.search || '');
    const filter = (next) => router.get(route('admin.networks.index'), { search, status: filters.status, ...next }, { preserveState: true, replace: true });
    const decision = (id, value, exit = false) => router.patch(route(exit ? 'admin.networks.exit' : 'admin.networks.decision', id), { decision: value }, { preserveScroll: true });
    return <AdminLayout header="Jaringan Cabang"><Head title="Jaringan Cabang" />
        <Breadcrumb items={[{ label: 'SaaS' }, { label: 'Jaringan Cabang' }]} homeHref={route('admin.dashboard')} />
        <div className="max-w-7xl space-y-5">
        <section className="rounded-2xl border border-slate-200/70 bg-white p-6 shadow-sm shadow-slate-200/40 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-600">Control room</p><div className="mt-1 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900">Jaringan tenant</h1><p className="mt-2 text-sm leading-6 text-slate-500">Persetujuan, tanggal efektif, pelepasan, dan audit dalam satu layar.</p></div><div className="flex gap-6"><div><p className="text-2xl font-black text-slate-900">{centrals.length}</p><p className="text-xs text-slate-400">tenant pusat</p></div><div><p className="text-2xl font-black text-slate-900">{relationships.total}</p><p className="text-xs text-slate-400">relasi tercatat</p></div></div></div></section>
        <section className="overflow-hidden rounded-2xl border border-slate-200/70 bg-white shadow-sm shadow-slate-200/40"><div className="flex flex-wrap gap-3 border-b border-slate-100 p-4"><form onSubmit={(e) => { e.preventDefault(); filter({}); }} className="flex min-w-64 flex-1 gap-2"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari pusat atau cabang" className="min-w-0 flex-1 rounded-xl border-slate-200 text-sm" /><button className="rounded-xl bg-slate-950 px-4 text-xs font-black text-white">Cari</button></form><select value={filters.status} onChange={(e) => filter({ status: e.target.value })} className="rounded-xl border-slate-200 text-sm"><option value="">Semua status</option>{Object.entries(labels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></div>
            <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Pusat → cabang</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Waktu</th><th className="px-5 py-3 text-right">Keputusan</th></tr></thead><tbody className="divide-y divide-slate-100">{relationships.data.map((row) => <tr key={row.id}><td className="px-5 py-4"><p className="font-black text-slate-800">{row.parent_tenant.name} <span className="mx-2 text-slate-300">→</span> {row.branch_tenant.name}</p><p className="mt-1 text-xs text-slate-400">Kode {row.network_code_used} · owner {row.branch_tenant.owner?.name || '—'}</p></td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase text-slate-600">{labels[row.status] || row.status}</span></td><td className="px-5 py-4 text-xs text-slate-500"><p>Diajukan {date(row.requested_at)}</p>{row.billing_effective_at && <p className="mt-1">Efektif {date(row.billing_effective_at)}</p>}</td><td className="px-5 py-4"><div className="flex justify-end gap-2">{row.status === 'pending_admin_approval' && <><button onClick={() => decision(row.id,'reject')} className="rounded-lg px-3 py-2 text-xs font-black text-rose-600">Tolak</button><button onClick={() => decision(row.id,'approve')} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-black text-white">Setujui</button></>}{row.status === 'exit_requested' && <><button onClick={() => decision(row.id,'reject',true)} className="rounded-lg px-3 py-2 text-xs font-black text-slate-500">Tolak</button><button onClick={() => decision(row.id,'approve',true)} className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-black text-white">Jadwalkan lepas</button></>}</div></td></tr>)}{relationships.data.length === 0 && <tr><td colSpan="4" className="py-16 text-center text-slate-400">Tidak ada relasi sesuai filter.</td></tr>}</tbody></table></div><div className="border-t border-slate-100 p-4"><Pagination links={relationships.links} /></div>
        </section>
        <section className="grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200/70 bg-white p-5 shadow-sm shadow-slate-200/40"><h2 className="font-black text-slate-900">Tenant pusat</h2><div className="mt-3 divide-y divide-slate-100">{centrals.map((central) => <div key={central.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-bold text-slate-700">{central.name}</p><p className="font-mono text-xs text-indigo-600">{central.branch_network_code}</p></div><div className="flex items-center gap-2"><span className="text-xs font-bold text-slate-400">{central.open_branches_count} cabang</span><button onClick={() => { const code = window.prompt('Kode jaringan baru', central.branch_network_code); if (code) router.patch(route('admin.networks.code.update', central.id), { branch_network_code: code }); }} className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-100 text-slate-500" title="Ubah kode"><i className="fi fi-rr-pencil" /></button></div></div>)}</div></article><article className="rounded-2xl border border-slate-200/70 bg-white p-5 shadow-sm shadow-slate-200/40"><h2 className="font-black text-slate-900">Audit impersonation</h2><div className="mt-3 max-h-80 divide-y divide-slate-100 overflow-auto">{auditLogs.map((log) => <div key={log.id} className="py-3"><p className="text-sm font-bold text-slate-700">{log.actor?.name || 'User terhapus'} → {log.branch_tenant.name}</p><p className="mt-1 text-xs text-slate-400">{date(log.started_at)} · {log.ended_at ? `selesai ${date(log.ended_at)}` : 'masih aktif'}</p></div>)}{auditLogs.length === 0 && <p className="py-8 text-center text-sm text-slate-400">Belum ada audit.</p>}</div></article></section>
        </div>
    </AdminLayout>;
}
