import Breadcrumb from '@/Components/Breadcrumb';
import Select from '@/Components/Select';
import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, router } from '@inertiajs/react';
import { useMemo, useState } from 'react';

const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value || 0);
const number = (value) => new Intl.NumberFormat('id-ID', { maximumFractionDigits: 2 }).format(value || 0);
const date = (value) => value ? new Date(`${String(value).slice(0, 10)}T00:00:00`).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
const inputDate = (value) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`;
const clean = (values) => Object.fromEntries(Object.entries(values).filter(([, value]) => value !== ''));

const tabs = [
    ['overview', 'Ringkasan', 'aging'],
    ['suppliers', 'Per supplier', 'suppliers'],
    ['items', 'Per barang', 'items'],
    ['prices', 'Riwayat harga', 'price_history'],
    ['valuation', 'Valuasi stok', 'valuation'],
    ['hpp', 'HPP aktual', 'hpp'],
];

function EmptyState({ title, note }) {
    return <div className="px-5 py-14 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-slate-100 text-slate-400"><i className="fi fi-rr-chart-histogram" /></span><p className="mt-3 text-sm font-bold text-slate-700">{title}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div>;
}

function SectionHeader({ eyebrow, title, note, total }) {
    return <div className="flex flex-col gap-2 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-indigo-600">{eyebrow}</p><h2 className="mt-1 font-black text-slate-950">{title}</h2><p className="mt-1 text-xs text-slate-500">{note}</p></div>{total !== undefined && <span className="text-xs font-bold text-slate-500">{total} baris</span>}</div>;
}

export default function Index({ filters, suppliers, periodLabel, summary, aging, supplierBreakdown, itemBreakdown, priceHistory, valuation, hpp }) {
    const [form, setForm] = useState(filters);
    const [tab, setTab] = useState('overview');
    const activeTab = tabs.find(([key]) => key === tab);
    const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
    const apply = (event) => {
        event.preventDefault();
        router.get(route('tenant.reports.purchases.index'), clean(form), { preserveState: true, replace: true });
    };
    const reset = () => {
        const today = new Date();
        const empty = { start_date: inputDate(new Date(today.getFullYear(), today.getMonth(), 1)), end_date: inputDate(today), supplier_id: '', item_type: '', search: '' };
        setForm(empty);
        router.get(route('tenant.reports.purchases.index'), clean(empty), { preserveState: true, replace: true });
    };
    const exportUrl = useMemo(() => route('tenant.reports.purchases.export', { ...clean(filters), section: activeTab?.[2] || 'aging' }), [filters, activeTab]);
    const summaryCards = [
        ['Total pembelian', money(summary.purchase_total), `${summary.purchase_count} dokumen`, 'fi-rr-shopping-cart', 'text-indigo-700 bg-indigo-50'],
        ['Pembayaran supplier', money(summary.supplier_payments), 'Kas keluar pada periode', 'fi-rr-money-bill-wave', 'text-sky-700 bg-sky-50'],
        ['Hutang berjalan', money(summary.running_payable), 'Saldo saat ini', 'fi-rr-wallet', 'text-rose-700 bg-rose-50'],
        ['Nilai persediaan', money(summary.inventory_value), 'Stok × HPP terbaru', 'fi-rr-boxes', 'text-emerald-700 bg-emerald-50'],
        ['HPP aktual', money(summary.actual_hpp), 'Snapshot stok keluar', 'fi-rr-coins', 'text-amber-700 bg-amber-50'],
    ];
    const agingCards = [
        ['Belum jatuh tempo', aging.not_due, 'bg-emerald-50 text-emerald-800 ring-emerald-100'],
        ['Terlambat 1–7 hari', aging.overdue_1_7, 'bg-amber-50 text-amber-900 ring-amber-100'],
        ['Terlambat 8–30 hari', aging.overdue_8_30, 'bg-orange-50 text-orange-900 ring-orange-100'],
        ['Terlambat >30 hari', aging.overdue_over_30, 'bg-rose-50 text-rose-900 ring-rose-100'],
    ];

    return (
        <AdminLayout header="Laporan Pembelian">
            <Head title="Laporan Pembelian" />
            <div className="print:hidden"><Breadcrumb items={[{ label: 'Laporan' }, { label: 'Pembelian' }]} /></div>
            <div className="space-y-5 print:space-y-3">
                <header className="relative overflow-hidden rounded-3xl bg-slate-950 p-6 text-white shadow-xl shadow-slate-300/30 print:rounded-none print:bg-white print:p-0 print:text-black print:shadow-none sm:p-8">
                    <div className="pointer-events-none absolute -right-16 -top-20 h-64 w-64 rotate-12 border-[34px] border-indigo-400/10 print:hidden" />
                    <div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
                        <div><p className="text-[10px] font-black uppercase tracking-[.24em] text-indigo-300 print:text-slate-500">Procurement intelligence</p><h1 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Laporan Pembelian</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300 print:text-slate-600">Pantau arus pembelian, harga pemasok, umur hutang, nilai persediaan, dan HPP aktual dalam satu buku kendali.</p><p className="mt-3 text-xs font-bold text-indigo-200 print:text-slate-600">Periode {periodLabel}</p></div>
                        <div className="flex flex-wrap gap-2 print:hidden"><button type="button" onClick={() => window.print()} className="rounded-xl bg-white/10 px-4 py-2.5 text-xs font-bold ring-1 ring-white/15 transition hover:bg-white/15"><i className="fi fi-rr-print mr-2" />Cetak</button><a href={exportUrl} className="rounded-xl bg-indigo-500 px-4 py-2.5 text-xs font-bold transition hover:bg-indigo-400"><i className="fi fi-rr-file-download mr-2" />Export {activeTab?.[1]}</a></div>
                    </div>
                </header>

                <form onSubmit={apply} className="rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm shadow-slate-200/40 print:hidden sm:p-5">
                    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">
                        <label><span className="text-xs font-bold text-slate-600">Mulai periode</span><input type="date" value={form.start_date} onChange={(event) => set('start_date', event.target.value)} className="mt-1.5 w-full rounded-xl border-slate-200 py-2.5 text-sm" /></label>
                        <label><span className="text-xs font-bold text-slate-600">Akhir periode</span><input type="date" value={form.end_date} onChange={(event) => set('end_date', event.target.value)} className="mt-1.5 w-full rounded-xl border-slate-200 py-2.5 text-sm" /></label>
                        <label><span className="text-xs font-bold text-slate-600">Supplier</span><Select value={form.supplier_id} onChange={(value) => set('supplier_id', value)} options={[{ value: '', label: 'Semua supplier' }, ...suppliers.map((supplier) => ({ value: String(supplier.id), label: supplier.name }))]} className="mt-1.5" searchPlaceholder="Cari supplier..." /></label>
                        <label><span className="text-xs font-bold text-slate-600">Jenis barang</span><Select value={form.item_type} onChange={(value) => set('item_type', value)} searchable={false} options={[{ value: '', label: 'Semua jenis' }, { value: 'product', label: 'Produk' }, { value: 'raw_material', label: 'Bahan baku' }]} className="mt-1.5" /></label>
                        <label><span className="text-xs font-bold text-slate-600">Cari barang</span><div className="relative mt-1.5"><i className="fi fi-rr-search pointer-events-none absolute left-3.5 top-3 text-sm text-slate-400" /><input value={form.search} onChange={(event) => set('search', event.target.value)} placeholder="Nama produk/bahan" className="w-full rounded-xl border-slate-200 py-2.5 pl-10 text-sm" /></div></label>
                    </div>
                    <p className="mt-3 text-[11px] leading-5 text-slate-500">Filter supplier memengaruhi pembelian, pembayaran, dan aging. Jenis barang memengaruhi pembelian barang, harga, dan valuasi; pencarian nama juga menyaring HPP penjualan.</p>
                    <div className="mt-4 flex justify-end gap-2 border-t border-slate-100 pt-4"><button type="button" onClick={reset} className="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-100">Reset</button><button className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-bold text-white hover:bg-slate-800">Terapkan</button></div>
                </form>

                <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{summaryCards.map(([label, value, note, icon, tone]) => <article key={label} className="rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm shadow-slate-200/30 print:shadow-none"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-xl font-black tracking-tight text-slate-950">{value}</p><p className="mt-1 text-[11px] text-slate-500">{note}</p></div><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${tone}`}><i className={`fi ${icon}`} /></span></div></article>)}</section>

                <nav className="flex gap-1 overflow-x-auto rounded-2xl border border-slate-200/80 bg-white p-1.5 shadow-sm shadow-slate-200/30 print:hidden">{tabs.map(([key, label]) => <button key={key} type="button" onClick={() => setTab(key)} className={`shrink-0 rounded-xl px-4 py-2.5 text-xs font-black transition ${tab === key ? 'bg-slate-950 text-white shadow-sm' : 'text-slate-600 hover:bg-slate-100'}`}>{label}</button>)}</nav>

                {tab === 'overview' && <section className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{agingCards.map(([label, bucket, tone]) => <article key={label} className={`rounded-2xl p-4 ring-1 ${tone}`}><p className="text-xs font-bold opacity-75">{label}</p><p className="mt-2 text-xl font-black">{money(bucket.amount)}</p><p className="mt-1 text-[11px] font-semibold opacity-65">{bucket.count} dokumen</p></article>)}</div><div className="grid gap-5 xl:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white"><SectionHeader eyebrow="Supplier utama" title="Pembelian terbesar" note="Berdasarkan nilai pembelian pada periode" />{supplierBreakdown.slice(0, 5).map((row, index) => <div key={row.supplier_id} className="flex items-center gap-3 border-t border-slate-100 px-5 py-3"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-slate-100 text-xs font-black text-slate-500">{index + 1}</span><p className="min-w-0 flex-1 truncate text-sm font-bold text-slate-700">{row.supplier_name}</p><p className="text-sm font-black text-slate-950">{money(row.purchase_total)}</p></div>)}{!supplierBreakdown.length && <EmptyState title="Belum ada pembelian" note="Ubah periode atau filter untuk melihat data." />}</article><article className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white"><SectionHeader eyebrow="Barang utama" title="Nilai pembelian terbesar" note="Biaya bersih setelah alokasi diskon dan biaya" />{itemBreakdown.slice(0, 5).map((row, index) => <div key={`${row.item_type}-${row.item_name}`} className="flex items-center gap-3 border-t border-slate-100 px-5 py-3"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-slate-100 text-xs font-black text-slate-500">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-700">{row.item_name}</p><p className="text-[10px] uppercase text-slate-400">{row.item_type === 'product' ? 'Produk' : 'Bahan baku'}</p></div><p className="text-sm font-black text-slate-950">{money(row.total_cost)}</p></div>)}{!itemBreakdown.length && <EmptyState title="Belum ada barang" note="Item pembelian akan tampil di sini." />}</article></div></section>}

                {tab === 'suppliers' && <section className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white"><SectionHeader eyebrow="Analisis supplier" title="Pembelian per supplier" note="Pembayaran periode dihitung berdasarkan tanggal pembayaran" total={supplierBreakdown.length} /><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Supplier</th><th className="px-4 py-3 text-right">Dokumen</th><th className="px-4 py-3 text-right">Pembelian</th><th className="px-4 py-3 text-right">Pembayaran periode</th><th className="px-5 py-3 text-right">Sisa dari dokumen</th></tr></thead><tbody className="divide-y divide-slate-100">{supplierBreakdown.map((row) => <tr key={row.supplier_id}><td className="px-5 py-4"><Link href={route('tenant.suppliers.show', row.supplier_id)} className="font-bold text-slate-800 hover:text-indigo-700">{row.supplier_name}</Link></td><td className="px-4 py-4 text-right text-slate-600">{row.purchase_count}</td><td className="px-4 py-4 text-right font-bold text-slate-900">{money(row.purchase_total)}</td><td className="px-4 py-4 text-right font-semibold text-emerald-700">{money(row.period_payments)}</td><td className="px-5 py-4 text-right font-bold text-rose-700">{money(row.outstanding)}</td></tr>)}</tbody></table></div>{!supplierBreakdown.length && <EmptyState title="Belum ada data supplier" note="Tidak ada pembelian pada periode terpilih." />}</section>}

                {tab === 'items' && <section className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white"><SectionHeader eyebrow="Analisis barang" title="Pembelian per barang" note="Rata-rata biaya dihitung tertimbang dari biaya persediaan bersih" total={itemBreakdown.length} /><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Barang</th><th className="px-4 py-3">Jenis</th><th className="px-4 py-3 text-right">Jumlah</th><th className="px-4 py-3 text-right">Dokumen</th><th className="px-4 py-3 text-right">Rata-rata biaya</th><th className="px-5 py-3 text-right">Total biaya</th></tr></thead><tbody className="divide-y divide-slate-100">{itemBreakdown.map((row) => <tr key={`${row.item_type}-${row.item_name}`}><td className="px-5 py-4 font-bold text-slate-800">{row.item_name}</td><td className="px-4 py-4 text-xs font-semibold text-slate-500">{row.item_type === 'product' ? 'Produk' : 'Bahan baku'}</td><td className="px-4 py-4 text-right text-slate-700">{number(row.quantity)} {row.unit_name}</td><td className="px-4 py-4 text-right text-slate-600">{row.purchase_count}</td><td className="px-4 py-4 text-right font-semibold text-slate-700">{money(row.average_unit_cost)}</td><td className="px-5 py-4 text-right font-black text-slate-950">{money(row.total_cost)}</td></tr>)}</tbody></table></div>{!itemBreakdown.length && <EmptyState title="Belum ada data barang" note="Tidak ada item pembelian yang sesuai filter." />}</section>}

                {tab === 'prices' && <section className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white"><SectionHeader eyebrow="Price ledger" title="Riwayat harga beli" note="Menampilkan maksimal 100 baris terbaru; export berisi seluruh hasil" total={priceHistory.length} /><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Tanggal / dokumen</th><th className="px-4 py-3">Barang</th><th className="px-4 py-3">Supplier</th><th className="px-4 py-3 text-right">Harga faktur</th><th className="px-5 py-3 text-right">Biaya bersih</th></tr></thead><tbody className="divide-y divide-slate-100">{priceHistory.map((row) => <tr key={row.id}><td className="px-5 py-4"><Link href={route('tenant.purchases.show', row.purchase_id)} className="font-mono text-xs font-bold text-indigo-700 hover:underline">{row.purchase_number}</Link><p className="mt-1 text-xs text-slate-500">{date(row.purchase_date)}</p></td><td className="px-4 py-4"><p className="font-bold text-slate-800">{row.item_name}</p><p className="mt-1 text-xs text-slate-500">{number(row.quantity)} {row.unit_name}</p></td><td className="px-4 py-4 text-slate-700">{row.supplier_name}</td><td className="px-4 py-4 text-right font-semibold text-slate-700">{money(row.unit_cost)}</td><td className="px-5 py-4 text-right font-black text-slate-950">{money(row.net_unit_cost)}</td></tr>)}</tbody></table></div>{!priceHistory.length && <EmptyState title="Belum ada histori harga" note="Harga beli akan tercatat setelah pembelian diposting." />}</section>}

                {tab === 'valuation' && <section className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><article className="rounded-2xl bg-slate-950 p-4 text-white"><p className="text-xs font-bold text-slate-400">Total persediaan</p><p className="mt-2 text-2xl font-black">{money(valuation.summary.total)}</p></article><article className="rounded-2xl bg-indigo-50 p-4 text-indigo-900 ring-1 ring-indigo-100"><p className="text-xs font-bold opacity-70">Produk</p><p className="mt-2 text-xl font-black">{money(valuation.summary.products)}</p></article><article className="rounded-2xl bg-emerald-50 p-4 text-emerald-900 ring-1 ring-emerald-100"><p className="text-xs font-bold opacity-70">Bahan baku</p><p className="mt-2 text-xl font-black">{money(valuation.summary.raw_materials)}</p></article></div><section className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white"><SectionHeader eyebrow="Inventory ledger" title="Valuasi persediaan berjalan" note="Saldo stok saat ini dikali HPP rata-rata terbaru" total={valuation.rows.length} /><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Barang</th><th className="px-4 py-3">Jenis</th><th className="px-4 py-3 text-right">Stok</th><th className="px-4 py-3 text-right">HPP rata-rata</th><th className="px-5 py-3 text-right">Nilai</th></tr></thead><tbody className="divide-y divide-slate-100">{valuation.rows.map((row) => <tr key={row.id}><td className="px-5 py-4"><p className="font-bold text-slate-800">{row.item_name}</p>{!row.is_active && <p className="mt-1 text-[10px] font-bold uppercase text-slate-400">Nonaktif</p>}</td><td className="px-4 py-4 text-xs text-slate-500">{row.item_type === 'product' ? 'Produk' : 'Bahan baku'}</td><td className="px-4 py-4 text-right text-slate-700">{number(row.stock)} {row.unit_name}</td><td className="px-4 py-4 text-right font-semibold text-slate-700">{money(row.average_cost)}</td><td className="px-5 py-4 text-right font-black text-slate-950">{money(row.value)}</td></tr>)}</tbody></table></div>{!valuation.rows.length && <EmptyState title="Belum ada persediaan" note="Tidak ada barang yang sesuai filter." />}</section></section>}

                {tab === 'hpp' && <section className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><article className="rounded-2xl bg-sky-50 p-4 text-sky-900 ring-1 ring-sky-100"><p className="text-xs font-bold opacity-70">Pendapatan item</p><p className="mt-2 text-xl font-black">{money(hpp.summary.revenue)}</p></article><article className="rounded-2xl bg-amber-50 p-4 text-amber-900 ring-1 ring-amber-100"><p className="text-xs font-bold opacity-70">HPP aktual</p><p className="mt-2 text-xl font-black">{money(hpp.summary.cost)}</p></article><article className="rounded-2xl bg-emerald-50 p-4 text-emerald-900 ring-1 ring-emerald-100"><p className="text-xs font-bold opacity-70">Laba kotor item</p><p className="mt-2 text-xl font-black">{money(hpp.summary.gross_profit)}</p></article></div><section className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white"><SectionHeader eyebrow="Cost snapshot" title="HPP aktual per transaksi" note="Menggunakan snapshot mutasi stok; data lama memakai snapshot item transaksi" total={hpp.rows.length} /><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Transaksi</th><th className="px-4 py-3">Barang</th><th className="px-4 py-3 text-right">Pendapatan</th><th className="px-4 py-3 text-right">HPP aktual</th><th className="px-5 py-3 text-right">Laba kotor</th></tr></thead><tbody className="divide-y divide-slate-100">{hpp.rows.map((row) => <tr key={row.id}><td className="px-5 py-4"><p className="font-mono text-xs font-bold text-slate-800">{row.invoice_number}</p><p className="mt-1 text-xs text-slate-500">{date(row.transaction_date)}</p></td><td className="px-4 py-4"><p className="font-bold text-slate-800">{row.item_name}</p><p className="mt-1 text-xs text-slate-500">{number(row.quantity)} item</p></td><td className="px-4 py-4 text-right font-semibold text-slate-700">{money(row.revenue)}</td><td className="px-4 py-4 text-right font-bold text-amber-800">{money(row.actual_cost)}</td><td className={`px-5 py-4 text-right font-black ${row.gross_profit >= 0 ? 'text-emerald-700' : 'text-rose-700'}`}>{money(row.gross_profit)}</td></tr>)}</tbody></table></div>{!hpp.rows.length && <EmptyState title="Belum ada HPP aktual" note="Transaksi penjualan pada periode akan tampil di sini." />}</section></section>}
            </div>
        </AdminLayout>
    );
}
