import Breadcrumb from '@/Components/Breadcrumb';
import Pagination from '@/Components/Pagination';
import AdminLayout from '@/Layouts/AdminLayout';
import usePermission from '@/Hooks/usePermission';
import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';

const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value || 0);
const empty = { name: '', phone: '', email: '', address: '', contact_name: '', note: '', is_active: true };

export default function Index({ suppliers, filters }) {
    const can = usePermission(); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false);
    const form = useForm(empty);
    const showForm = (supplier = null) => { setEditing(supplier); form.setData(supplier ? { ...empty, ...supplier } : empty); form.clearErrors(); setOpen(true); };
    const submit = (e) => { e.preventDefault(); const options = { preserveScroll: true, onSuccess: () => { setOpen(false); form.reset(); } }; editing ? form.put(route('tenant.suppliers.update', editing.id), options) : form.post(route('tenant.suppliers.store'), options); };
    return <AdminLayout header="Supplier"><Head title="Supplier" /><Breadcrumb items={[{ label: 'Master Data' }, { label: 'Supplier' }]} />
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-600">Mitra pasokan</p><h2 className="mt-1 text-2xl font-bold text-slate-900">Supplier</h2><p className="mt-1 text-sm text-slate-500">Kontak dan posisi hutang dalam satu tempat.</p></div>{can('suppliers.create') && <button onClick={() => showForm()} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">+ Supplier baru</button>}</div>
        <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-4"><input defaultValue={filters.search} onChange={(e) => router.get(route('tenant.suppliers.index'), e.target.value ? { search: e.target.value } : {}, { preserveState: true, replace: true })} placeholder="Cari supplier..." className="w-full max-w-sm rounded-xl border-slate-200 text-sm" /></div>
            <div className="divide-y divide-slate-100">{suppliers.data.map((supplier) => <button key={supplier.id} onClick={() => can('suppliers.edit') && showForm(supplier)} className="grid w-full grid-cols-[1fr_auto] gap-4 p-4 text-left hover:bg-slate-50"><div><div className="font-semibold text-slate-900">{supplier.name}</div><div className="mt-1 text-xs text-slate-500">{supplier.contact_name || 'Tanpa PIC'} · {supplier.phone || 'Tanpa nomor'}</div></div><div className="text-right"><div className="font-semibold text-slate-900">{money(supplier.payable_total)}</div><div className={`text-xs ${supplier.is_active ? 'text-emerald-600' : 'text-slate-400'}`}>{supplier.is_active ? 'Aktif' : 'Nonaktif'}</div></div></button>)}</div>
            {!suppliers.data.length && <div className="p-10 text-center text-sm text-slate-500">Belum ada supplier.</div>}<div className="border-t border-slate-100 p-4"><Pagination links={suppliers.links} /></div></div>
        {open && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={submit} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-bold text-slate-900">{editing ? 'Ubah supplier' : 'Supplier baru'}</h3><button type="button" onClick={() => setOpen(false)} className="text-slate-400">✕</button></div><div className="grid gap-4 sm:grid-cols-2">{[['name','Nama supplier *'],['contact_name','Nama kontak'],['phone','Telepon / WhatsApp'],['email','Email']].map(([key,label]) => <label key={key} className="text-sm text-slate-600">{label}<input value={form.data[key] || ''} onChange={(e) => form.setData(key,e.target.value)} className="mt-1 w-full rounded-xl border-slate-200" />{form.errors[key] && <small className="text-rose-600">{form.errors[key]}</small>}</label>)}<label className="sm:col-span-2 text-sm text-slate-600">Alamat<textarea value={form.data.address || ''} onChange={(e) => form.setData('address',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data.is_active} onChange={(e) => form.setData('is_active',e.target.checked)} /> Supplier aktif</label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-xl border px-4 py-2">Batal</button><button disabled={form.processing} className="rounded-xl bg-indigo-600 px-4 py-2 font-semibold text-white">Simpan</button></div></form></div>}
    </AdminLayout>;
}
