plugins {
    id 'com.android.application'
}

android {
    namespace 'id.rancaka.printbridge'
    compileSdk 35

    defaultConfig {
        applicationId 'id.rancaka.printbridge'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = 'printer-rancaka.apk'
        }
    }
}
