import BrandLogo from '@/Components/BrandLogo';
import { Head, router, useForm } from '@inertiajs/react';

export default function StoreOnboarding({ user, referralCode = '', networkCode = '', accountType = 'standalone', branchNetworkEnabled = false }) {
    const form = useForm({ store_name: '', phone: '', address: '', username: user.username, referral_code: referralCode, network_code: networkCode, account_type: accountType });
    const branch = form.data.account_type === 'branch';
    const choose = (type) => form.setData((data) => ({ ...data, account_type: type, referral_code: type === 'branch' ? '' : data.referral_code, network_code: type === 'standalone' ? '' : data.network_code }));
    return <><Head title="Lengkapi Toko" /><div className="min-h-screen bg-slate-100 px-5 py-10"><div className="mx-auto w-full max-w-2xl rounded-[2rem] border border-slate-200 bg-white p-7 shadow-xl shadow-slate-200/60 sm:p-10">
        <div className="flex items-center justify-between"><div className="flex items-center gap-3"><BrandLogo className="h-11 w-11" /><div><p className="font-black text-slate-900">Selamat datang, {user.name}</p><p className="text-xs text-slate-500">{user.email}</p></div></div>{user.avatar_url && <img src={user.avatar_url} alt="" className="h-11 w-11 rounded-full" />}</div>
        <div className="mt-8"><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-black text-indigo-700">Langkah terakhir</span><h1 className="mt-3 text-3xl font-black tracking-tight text-slate-950">Bentuk toko Anda</h1><p className="mt-1 text-sm text-slate-500">Data operasional tetap milik toko, termasuk ketika bergabung sebagai cabang.</p></div>
        {branchNetworkEnabled && <div className="mt-6 grid grid-cols-2 gap-3">{[['standalone','Toko mandiri'],['branch','Cabang jaringan']].map(([value,label]) => <button type="button" key={value} onClick={() => choose(value)} className={`rounded-xl border px-4 py-3 text-sm font-black ${form.data.account_type === value ? 'border-slate-950 bg-slate-950 text-white' : 'border-slate-200 text-slate-500'}`}>{label}</button>)}</div>}
        <form onSubmit={(event) => { event.preventDefault(); form.post(route('onboarding.store.store')); }} className="mt-7 space-y-4">
            {[['store_name','Nama toko','Contoh: Kedai Bahagia'],['phone','Nomor WhatsApp','08xxxxxxxxxx'],['username','Username akun','Username dapat diganti lagi nanti']].map(([key,label,placeholder]) => <div key={key}><label htmlFor={key} className="mb-1.5 block text-sm font-bold text-slate-700">{label} <span className="text-rose-500">*</span></label><input id={key} value={form.data[key]} onChange={(e) => form.setData(key,e.target.value)} placeholder={placeholder} className="w-full rounded-xl border-slate-200 text-sm" />{form.errors[key] && <p className="mt-1 text-xs text-rose-600">{form.errors[key]}</p>}</div>)}
            <div><label htmlFor="address" className="mb-1.5 block text-sm font-bold text-slate-700">Alamat toko <span className="font-normal text-slate-400">(opsional)</span></label><textarea id="address" value={form.data.address} onChange={(e) => form.setData('address',e.target.value)} className="w-full rounded-xl border-slate-200 p-3 text-sm" /></div>
            {branch ? <div><label htmlFor="network_code" className="mb-1.5 block text-sm font-bold text-slate-700">Kode jaringan pusat <span className="text-rose-500">*</span></label><input id="network_code" value={form.data.network_code} onChange={(e) => form.setData('network_code',e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,''))} className="w-full rounded-xl border-slate-200 font-bold uppercase tracking-wide" />{form.errors.network_code && <p className="mt-1 text-xs text-rose-600">{form.errors.network_code}</p>}</div> : <div><label htmlFor="referral_code" className="mb-1.5 block text-sm font-bold text-slate-700">Kode referral <span className="font-normal text-slate-400">(opsional)</span></label><input id="referral_code" value={form.data.referral_code} onChange={(e) => form.setData('referral_code',e.target.value.toUpperCase().replace(/\s/g,''))} className="w-full rounded-xl border-slate-200 font-bold uppercase tracking-wide" />{form.errors.referral_code && <p className="mt-1 text-xs text-rose-600">{form.errors.referral_code}</p>}</div>}
            <button disabled={form.processing} className="w-full rounded-xl bg-indigo-600 px-4 py-3 text-sm font-black text-white hover:bg-indigo-700">{branch ? 'Kirim Pengajuan Cabang' : 'Buat Toko & Mulai Trial 7 Hari'}</button>
        </form><button type="button" onClick={() => router.post(route('logout'))} className="mt-4 w-full text-sm font-bold text-slate-400 hover:text-slate-600">Keluar dari akun</button>
    </div></div></>;
}
